name = "Tns Server"
author = "TheDeathlyCow"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e070aa9a4eec0f0e8eb83140867cee697b432466886fffee6793081105abca25"

[versions]
fabric = "0.19.5"
minecraft = "26.3"
