name = "Tns Server"
author = "TheDeathlyCow"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "04b8f08925cd0c0161806b5b12b624b228f9dd4fb0ed754c27da23bda05c86d7"

[versions]
fabric = "0.19.5"
minecraft = "26.3"
