name = "Tns Server"
author = "TheDeathlyCow"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "07f4e70862b323f2def17f0602e71d545f618430d84a5508d0718ac2e73433b4"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
